name: goreadme
on:
  push:
    branches: [main]
permissions:
  pull-requests: write
  contents: write
jobs:
  goreadme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          git config --global --add safe.directory /home/runner/work/x/x
          git config --global --add safe.directory /github/workspace
          git config --global --add safe.directory /github/home

      - uses: posener/goreadme@v1
        with:
          title: github.com/cmattoon/x
          import-path: github.com/cmattoon/x
          badge-godoc: 'true'
          badge-codecov: 'true'
          badge-golangci: 'true'
          badge-goreportcard: 'true'
          constants: 'true'
          factories: 'true'
          functions: 'true'
          methods: 'true'
          variabless: 'true'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
